<a href="https://colab.research.google.com/github/yusun-shin/python_programming/blob/main/11%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install numpy


In [ ]:
import numpy as np

In [ ]:
a=np.arange(6)


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a2=a [np.newaxis,:]

In [ ]:
a2.shape

(1, 6)

In [ ]:
a.shape

(6,)

In [ ]:
a=[]

In [ ]:
a=[0,1,2,3,4,5]

In [ ]:
a

[0, 1, 2, 3, 4, 5]

In [ ]:
a[0]

0

In [ ]:
a[6]

IndexError: list index out of range

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,1]

np.int64(2)

In [ ]:
 a[2]

array([ 9, 10, 11, 12])

How to create a basic array

In [ ]:
a=np.array([1,2,3])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty(2)

array([0., 0.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
np.arange(2,8,2)

array([2, 4, 6])

In [ ]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a=1.

In [ ]:
a

1.0

In [ ]:
type(a)

float

In [ ]:
b=np.ones(2,dtype=np.int64)

In [ ]:
b

array([1, 1])

# Adding,removing, and sorting elements

In [ ]:
arr=np.array([2,1,5,3,7,4,6,8])

In [ ]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a=np.sort(arr)

In [ ]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a=np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a.shape

(6,)

In [ ]:
a2=a[np.newaxis,:]

In [ ]:
a2.shape

(1, 6)

In [ ]:
row_vector=a[np.newaxis,:]

In [ ]:
row_vector.shape

(1, 6)

In [ ]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data[1]

np.int64(2)

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
print(a[a<5])

[1 2 3 4]


In [ ]:
b=2

In [ ]:
if b>5:
  print("에구 너무 큰데요")
else:
  print("좋아요!")

좋아요!


In [ ]:
a>=5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[(a>5)|(a==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b=np.nonzero(a<5)

In [ ]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [ ]:
list(zip(b[0],b[1]))

[(np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1)),
 (np.int64(0), np.int64(2)),
 (np.int64(0), np.int64(3))]

# How to create an array from existing data

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1=a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
a1

array([[1, 1],
       [2, 2]])

In [ ]:
a2

array([[3, 3],
       [4, 4]])

In [ ]:
np.vstack(((a1,a2)))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
a = np.arange(1,15)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
np.hsplit(x,(3,6))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2,3]

np.int64(12)

In [ ]:
b1=a.copy()

In [ ]:
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b1[0]=99

In [ ]:
b1

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [ ]:
data=np.array([1,2])

In [ ]:
ones=np.ones(2,dtype=int)

In [ ]:
data+ones

array([2, 3])

In [ ]:
data-ones

array([0, 1])

In [ ]:
data*ones

array([1, 2])

In [ ]:
data/data

array([1., 1.])

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a.sum()

np.int64(10)

In [ ]:
b=np.array([[1,1],[2,2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=1)

array([2, 4])

**Broadcasting**

In [ ]:
data=np.array([1.0,2.0])

In [ ]:
data*1.6

array([1.6, 3.2])

# More useful array operations

In [ ]:
data.max()

np.float64(2.0)

In [ ]:
data.min()

np.float64(1.0)

In [ ]:
b=np.array([[1,4],[2,7]])

In [ ]:
b

array([[1, 4],
       [2, 7]])

In [ ]:
b.min()

np.int64(1)

In [ ]:
b.min(axis=0)

array([1, 4])

In [ ]:
c = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
c.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Cretating Matrices

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0,1]

np.int64(2)

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2,0]

array([1, 3])

In [ ]:
data.max()

np.int64(6)

In [ ]:
data.min()

np.int64(1)

In [ ]:
data.sum()

np.int64(21)

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

In [ ]:
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

**Generating Random numbers**

# How to get unique items and counts

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


# Transposing and reshaping a matrix

In [ ]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)

In [ ]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()

In [ ]:
a1[0] = 99

In [ ]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = x.ravel()

In [ ]:
a2[0] = 98

In [ ]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
